set -ga terminal-features ",xterm-kitty:RGB"
set -g set-clipboard on

# 
# Keybinds
# 

# new panes
unbind %
bind + split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
# new window
bind c new-window -c "#{pane_current_path}"

# closing windows, panes, sessions
bind-key x kill-pane
bind-key X kill-window
bind-key k confirm-before -p "Kill session? (y/n)" kill-session

# Alt+hjkl to switch panes (vim-style)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# pop up terminals

unbind t

bind -T prefix t switch-client -T terminal
# empty terminal
bind -T terminal t display-popup -E "$SHELL"
# lazygit
bind -T terminal l display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

#
# Styling
#

# Panes
set -g pane-border-style "fg=#{@border_grey}"
set -g pane-active-border-style "fg=#{@window_bg}"

# Messages / copy mode
set -g message-style "bg=#{@status_fg},fg=#{@window_bg}"
set -g mode-style "bg=#{@right_bg},fg=#{@status_fg}"

# Status bar
# Keep unused status area transparent/default
set -g status-style "bg=default,fg=#{@status_fg}"
set -g status-justify left
set -g status-left ""

# Window container
set -g window-status-separator ""

set -g window-status-format \
'#{?window_start_flag,#[fg=#{@window_bg} bg=default],}#[fg=#{@status_fg} bg=#{@window_bg}] #I:#W #{?window_end_flag,#[fg=#{@window_bg} bg=default],}'

set -g window-status-current-format \
'#{?window_start_flag,#[fg=#{@window_bg} bg=default],}#[fg=#{@status_fg} bg=#{@window_bg} bold] [ #I:#W ] #{?window_end_flag,#[fg=#{@window_bg} bg=default nobold],}'

# Right-side information
set -g status-right-length 100
set -g status-right \
'#[fg=#{@right_bg} bg=default]#[fg=#{@status_fg} bg=#{@right_bg}] #S | #{b:pane_current_path} #[fg=#{@right_bg} bg=default]'
